version: '2.4'

services:
  myskills-api:
    build:
      context: .
      target: base
    volumes:
      - ./lib:/app/lib
      - ./test:/app/test
      - ./.git:/app/.git
    command: npm run dev
    environment:
      - REDIS_API_HOST=myskills-redis
      - REDIS_API_PORT=6379
      - SERVER_PORT=3000
      - DOMAIN_HOST=myskills-api
      - MYDATA_OPERATOR=http://mydata-operator:4000
      - MYDATA_APP=http://mydata-app:1337
    depends_on:
      - mydata-operator
    ports:
      - 3000:3000
    networks:
      myskills-dev:
        aliases:
          - myskills-api
  myskills-redis:
    image: redis:5.0
    ports:
      - 6380:6379
    networks:
      myskills-dev:
        aliases:
          - myskills-redis
  mydata-operator-redis:
    image: redis:5.0
    ports:
      - 6379:6379
    networks:
      myskills-dev:
        aliases:
          - mydata-operator-redis
  mydata-operator-postgres:
    image: postgres:11.2
    ports:
      - 5432:5432
    networks:
      myskills-dev:
        aliases:
          - mydata-operator-postgres
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=mydata
      - POSTGRES_INITDB_ARGS=--encoding=utf8
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgresuser -d mydata']
      interval: 10s
      timeout: 5s
      retries: 5
  mydata-operator:
    image: jobtechswe/mydata-operator:latest
    command: >
      bash -c "npm run migrate up
      && npm start"
    ports:
      - 4000:4000
    networks:
      myskills-dev:
        aliases:
          - mydata-operator
    environment:
      - PORT=4000
      - PGHOST=mydata-operator-postgres
      - PGUSER=postgresuser
      - PGPASSWORD=postgrespassword
      - PGDATABASE=mydata
      - PGPORT=5432
      - DATABASE_URL=postgres://postgresuser:postgrespassword@mydata-operator-postgres:5432/mydata
      - REDIS=redis://mydata-operator-redis:6379/
      - NODE_ENV=development
    depends_on:
      mydata-operator-postgres:
        condition: service_healthy
      mydata-operator-redis:
        condition: service_started

  mydata-app: #This replaces the phone app in the normal flow.
    image: jobtechswe/mydata-app
    environment:
      - OPERATOR_URL=http://mydata-operator:4000/api
    ports:
      - 1337:1337
    networks:
      myskills-dev:
        aliases:
          - mydata-app

networks:
  myskills-dev:
    external:
      name: myskills-dev
