apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: ci
  name: api-ci
spec:
  host: api.myskills-ci.dev.services.jtech.se
  port:
    targetPort: http
  to:
    kind: Service
    name: api-ci
    weight: 100
  wildcardPolicy: None
