apiVersion: v1
kind: BuildConfig
metadata:
  name: myskills-api
  namespace: myskills
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "myskills-api:latest"
  resources:
    limits:
      memory: 1Gi # Nodes have low resources by default. We need higher memory for our build
  runPolicy: Serial
  source:
    git:
      ref: feature/ci
      uri: "https://github.com/JobtechSwe/myskills-api"
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
    - github:
        secretReference:
          name: github-webhook-secret
      type: GitHub
---
apiVersion: v1
kind: ImageStream
metadata:
  name: myskills-api
  namespace: myskills
spec:
  tags:
    - name: latest
      referencePolicy:
        type: Source
